name: alfred_clean
version: 1.0.1+3

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.1.2
  http: 1.1.0
  cupertino_icons: ^1.0.8
  kakao_flutter_sdk_user: ^1.9.7+3
  webview_flutter: ^4.7.0
  webview_flutter_android: ^4.3.4  # 기조 3.12.0 대신 최신 버전으로 업데이트
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.2.0
  intl: ^0.20.2
  fluttertoast: ^8.2.1
  url_launcher: ^6.3.1
  google_fonts: ^4.0.4
  extended_image: ^8.1.1
  cached_network_image: ^3.3.1
  flutter_inappwebview: ^6.0.0
  youtube_player_flutter: ^9.1.1
  lottie: ^3.3.1
  youtube_player_iframe: ^5.2.1
  shimmer: ^3.0.0
  another_flushbar: ^1.10.30
  flutter_staggered_grid_view: ^0.7.0
  dio: ^5.0.0
  google_mobile_ads: ^6.0.0
  flutter_hooks: ^0.21.2
  permission_handler: ^12.0.0+1
  record: ^6.0.0
  device_info_plus: ^11.5.0
  package_info_plus: ^8.0.2
  firebase_messaging: ^15.2.7
  uuid: ^4.4.0
  app_tracking_transparency: ^2.0.4
  sign_in_with_apple: ^6.1.2
  flutter_svg: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/butler_logo.png
    - assets/images/kakao_login_button.png
    - assets/transparent.png
    - assets/icon/apple_login.svg
    - assets/icon/apple_login_button.svg
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/alfred_icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  android: true
  ios: true
  android_12:
    color: "#FFFFFF"
    icon_background_color: "#FFFFFF"
    image: assets/transparent.png