name: alfred_clean

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.0.0
  http: ^0.13.6
  cupertino_icons: ^1.0.8
  kakao_flutter_sdk_user: ^1.4.2
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.4  # 기존 3.12.0 대신 최신 버전으로 업데이트
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  fluttertoast: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/butler_logo.png
    - assets/images/kakao_login_button.png
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf